### ISSUE TITLE
iOS 17: Type mismatch: ButtonAction is not () -> ()

### ISSUE THREAD

**Issue by yuntan** [nalexn/ViewInspector#249]
I've encountered the error with Xcode 15.0 beta and iOS 17 beta.

- Xcode 15.0 beta and iOS 16.4 (simulator): test passed.
- Xcode 15.0 beta and iOS 17 beta (real device): Type mismatch: ButtonAction is not () -> ()

<img width="718" alt="スクリーンショット 2023-06-15 10 58 56" src="https://github.com/nalexn/ViewInspector/assets/574575/84a52c31-0420-4c6d-9008-742e0cd03402">

The test code is following:

```
final class ViewInspectorCrashTests: XCTestCase {
    func testExample() throws {
        let view = ContentView()
        let exp = view.inspection.inspect { v in
            XCTAssertFalse(try v.actualView().flag)
            try v.button().tap()
            XCTAssertTrue(try v.actualView().flag)
        }
        ViewHosting.host(view: view)
        wait(for: [exp], timeout: 10)
    }
}
```

The View code is following:

```
struct ContentView: View {
    @State var flag = false
    internal let inspection = Inspection<Self>()
    
    var body: some View {
        Button(action: {
            self.flag.toggle()
        }, label: { Text(flag ? "True" : "False") })
        .onReceive(inspection.notice) { self.inspection.visit(self, $0) }
    }
}
```

**Comment by nalexn** [comment]
Thanks for the report! That's fixed now in v0.9.7

**Comment by MarwanAziz** [comment]
I'm on v0.9.10 and still having this issue?! any help?

My code is like this

```
Button(email()) {
        viewModel.emailAction()
      }
      .id(emailButton)
```
The test looks like this

```
let downloadButton = try questionnaireCardView.inspect().find(viewWithId: emailButton).button()
XCTAssertNoThrow(try downloadButton.tap())
```
But I'm still getting the following error:
`XCTAssertNoThrow failed: threw error "Type mismatch: ButtonAction is not () -> ()"`
on this line `XCTAssertNoThrow(try downloadButton.tap())`
