### ISSUE TITLE
Dynamic query not finding view when there is conditional content

### ISSUE THREAD

**Issue by cfilipov** [nalexn/ViewInspector#69]
Given the following view:

```swift
struct ContentView: View {
    
    let showConditionalView = false
    
    var body: some View {
        Button(action: {}) {
            HStack(alignment: .center) {
                if showConditionalView {
                    Rectangle()
                }
                Text("Foo")
            }
        }
    }
}
```

This test will fail

```swift
extension ContentView: Inspectable { }

class Example: XCTestCase {

    func testExample() throws {
        let view = ContentView()
        let res = try view.inspect().findAll(ViewType.Text.self)
        XCTAssertGreaterThan(res.count, 0)
    }

}
```

`find` and `findAll` will not locate the `Text` view.

Manually inspecting the view hierarchy explicitly under the HStack like this will work: `view.inspect().findAll(ViewType.HStack.self).text(1)`. But of course that defeats the purpose of dynamic query.

If you comment out the conditional before the `Text("Foo")` the test case will correctly locate that view and pass.

**Comment by nalexn** [comment]
Thank you for finding this, @cfilipov ! I'll roll out a fix with the next version soon

**Comment by nalexn** [comment]
Fixed in v0.6.1

**Comment by a-shatou** [comment]
This issue still exists. I am using the last version - findAll always return an empty array.

**Comment by nalexn** [comment]
@a-shatou can you try `find` instead of 'findAll' to see if it reports any blocking views? You might be missing `Inspectable` conformance
